name: My Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: My Step
        run: echo "This step is running on a push or pull request to the main branch!"